summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
summon villager ~ ~ ~
setblock ~ ~ ~ air